- hosts: docker
  become: true
  tasks:
   - name: aptstuff
     apt: 
       name:
       - "apt-transport-https"
       - "ca-certificates"
       - "curl"
       - "gnupg-agent"
       - "software-properties-common"
       state: latest
       update_cache: yes  
   - name: dockerkey
     apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
   - name: addrepo
     apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
   - name: updateinstalldoc
     apt:
       name:
       - "docker-ce"
       - "docker-ce-cli"
       - "containerd.io"  
       update_cache: yes
       state: latest
   - name: dockgroup
     user:
       name: gergelykomuves
       groups: docker
       append: yes
